version: '3.8'

services:
  service1:
    image: service1
    build:
      context: ./DBservice
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/todos
      - QUEUE_NAME = todoQueue
    depends_on:
      - mongodb
 
  service2:
    image: service2
    build:
      context: ./managerService
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/todos
      - SERVICE1_URL=http://service1:3000  
      - QUEUE_NAME = todoQueue
    depends_on:
      - mongodb
      - service1 


  frontend:
    image: front
    build:
      context: ./zionet_project
    ports:
      - "5173:5173"
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
    depends_on:
      - service1  # Ensure service1 is ready before starting frontend
      - service2  # Ensure service2 is ready before starting frontend


  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:
