version: '3.8'

services:
  service1:
    image: service1
    build:
      context: ./DBservice
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/todos
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - QUEUE_NAME=todoQueue
    depends_on:
      - mongodb
      - rabbitmq

  service2:
    image: service2
    build:
      context: ./managerService
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/todos
      - SERVICE1_URL=http://service1:3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - QUEUE_NAME=todoQueue
    depends_on:
      - mongodb
      - service1
      - rabbitmq

  frontend:
    image: front
    build:
      context: ./zionet_project
    ports:
      - "5173:5173"
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
    depends_on:
      - service1
      - service2

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ AMQP port
      - "15672:15672"  # RabbitMQ management UI port
    networks:
      - mynetwork


  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "5000:80"   # Expose smtp4dev web UI on port 5000 of the host
      - "25:25"     # Expose SMTP port 25 of smtp4dev
      - "143:143"   # Expose IMAP port 143 of smtp4dev (for viewing emails)
    volumes:
      - ./path/to/save/messages:/var/mail
    environment:
      - DBTYPE=SQlite
    restart: unless-stopped
    networks:
      - mynetwork

   
networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:

